#spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata
#spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=create.sql
#spring.jpa.properties.hibernate.hbm2ddl.delimiter=;

# configuração banco Postgres

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bd_casa_do_codigo}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234567}


  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: update